version: "3.6"

services:
  api:
    build:
      context: ./packages/api
    command: yarn dev
    volumes:
      - ./packages/api:/usr/src/app
      - api_node_modules:/usr/src/app/node_modules
      - api_build:/usr/src/app/dist

  web:
    build:
      context: ./packages/web
    command: yarn dev
    volumes:
      - ./packages/web:/usr/src/app
      - web_node_modules:/usr/src/app/node_modules
      - web_build:/usr/src/app/.next

  postgres:
    ports:
      - 5432:5432

  redis:
    ports:
      - 6379:6379
