version: "3.6"

services:
  vpn:
    image: dperson/openvpn-client
    container_name: bobarr-vpn
    cap_add:
      - net_admin
    security_opt:
      - label:disable
    networks:
      - default
    dns:
      - 8.8.8.4
      - 1.0.0.1
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
#    ports:
#      - "51413:51413"
#      - "9117:9117"
    volumes:
      - /dev/net:/dev/net:z
      - ./packages/vpn:/vpn
    entrypoint: "bash -c"
    command: "exit 0"
    restart: always
    entrypoint: ["/sbin/tini", "--", "/usr/bin/openvpn.sh"]
    command: '-p "51413" -p "51413;udp" -f ""'
    tty: true

  api:
    links:
      - vpn:transmission
#      - vpn:jackett
    networks:
      - default

  transmission:
    network_mode: "service:vpn"
    depends_on:
      - vpn

  transmission-web:
    links:
      - vpn:transmission
    networks:
      - default

#  jackett:
#    network_mode: "service:vpn"
#    depends_on:
#      - vpn

#  jackett-web:
#    links:
#      - vpn:jackett
#    networks:
#      - default



